### ISSUE TITLE
EventMonitor crash on list index out of range.

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#215]
```

Process EventMonitor-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rms/vRMS/lib/python3.9/site-packages/RMS-0.1-py3.9-linux-x86_64.egg/RMS/EventMonitor.py", line 1992, in run
    self.getEventsAndCheck()
  File "/home/rms/vRMS/lib/python3.9/site-packages/RMS-0.1-py3.9-linux-x86_64.egg/RMS/EventMonitor.py", line 1974, in getEventsAndCheck
    self.checkEvents(self.config, test_mode=testmode)
  File "/home/rms/vRMS/lib/python3.9/site-packages/RMS-0.1-py3.9-linux-x86_64.egg/RMS/EventMonitor.py", line 1857, in checkEvents
    count, event.start_distance, event.start_angle, event.end_distance, event.end_angle, event.fovra, event.fovdec = self.trajectoryThroughFOV(event)
  File "/home/rms/vRMS/lib/python3.9/site-packages/RMS-0.1-py3.9-linux-x86_64.egg/RMS/EventMonitor.py", line 1560, in trajectoryThroughFOV
    if self.getPlateparFilePath(event) == "":
  File "/home/rms/vRMS/lib/python3.9/site-packages/RMS-0.1-py3.9-linux-x86_64.egg/RMS/EventMonitor.py", line 1359, in getPlateparFilePath
    platepar_file = self.getFile("platepar_cmn2010.cal", self.getDirectoryList(event)[0])[0]
IndexError: list index out of range

```
Maybe a problem specifically related to multi-camera gui systems.

**Comment by g7gpr** [comment]
Working on a solution for this; some field testing conducted. Need to build own station to replicate problem; which appears to require at least two unlikely events to occur at the same time.

**Comment by g7gpr** [comment]
Resolved and field tested.
