### ISSUE TITLE
SkyFit2 error messages 

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#297]
SkyFit2 was loaded, however would not display the fits image. The following errors appeared in console.

```
AttributeError: 'ImageItem' object has no attribute '_effectiveLut'
Traceback (most recent call last):
  File "/home/user/vRMS/lib/python3.11/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 616, in paint
    self.render()
  File "/home/user/source/RMS/RMS/Routines/CustomPyqtgraphClasses.py", line 678, in render
    if self._effectiveLut is None:
```
On
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
In every other way SkyFit2 was performing normally, star detected and star catalogue was working. A local fix replacing the 

```
self.__effectiveLut is None:
```
with 
```
True
```
Allowed SkyFit2 to run apparently normally.

**Comment by g7gpr** [comment]
Reinstalled, could not replicate issue.
