### ISSUE TITLE
AllskyPlot - matplot lib problem on Pi5 and Debian, checking Pi4

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#373]
On Pi5 running prerelease on standard distribution image. I'll check for similar issue on Pi4.

```
['Traceback (most recent call last):\n', '  File "/home/rms/source/RMS/RMS/Reprocess.py", line 263, in processNight\n
showerAssociation(config, [os.path.join(night_data_dir, ftpdetectinfo_name)], \\\n', 
'  File "/home/rms/source/RMS/Utils/ShowerAssociation.py", line 945, in showerAssociation\n    allsky_plot.beautify()\n', 
'  File "/home/rms/source/RMS/RMS/Routines/AllskyPlot.py", line 172, in beautify\n    self.fig.tight_layout()\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/figure.py", line 3540, in tight_layout\n    engine.execute(self)\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/layout_engine.py", line 183, in execute\n    kwargs = get_tight_layout_figure(\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/_tight_layout.py", line 266, in get_tight_layout_figure\n    kwargs = _auto_adjust_subplotpars(fig, renderer,\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/_tight_layout.py", line 82, in _auto_adjust_subplotpars\n    bb += [martist._get_tightbbox_for_layout_only(ax, renderer)]\n
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/artist.py", line 1411, in _get_tightbbox_for_layout_only\n    return obj.get_tightbbox(*args, **{**kwargs, "for_layout_only": True})\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper\n
    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 4418, in get_tightbbox\n    
bbox = a.get_tightbbox(renderer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/artist.py", line 366, in get_tightbbox\n
    bbox = self.get_window_extent(renderer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/text.py", line 956, in get_window_extent\n    bbox, info, descent = self._get_layout(self._renderer)\n
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/text.py", line 381, in _get_layout\n    
w, h, d = _get_text_metrics_with_cache(\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/text.py", line 69, in _get_text_metrics_with_cache\n    return _get_text_metrics_with_cache_impl(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/text.py", line 77, in _get_text_metrics_with_cache_impl\n    return renderer_ref().get_text_width_height_descent(text, fontprop, ismath)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 217, in get_text_width_height_descent\n    self.mathtext_parser.parse(s, self.dpi, prop)\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/mathtext.py", line 79, in parse\n
    return self._parse_cached(s, dpi, prop, antialiased)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 
'  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/mathtext.py", line 100, in _parse_cached\n
    box = self._parser.parse(s, fontset, fontsize, dpi)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
 '  File "/home/rms/vRMS/lib/python3.11/site-packages/matplotlib/_mathtext.py", line 2165, in parse\n
    raise ValueError("\\n" + ParseException.explain(err, 0)) from None\n', "ValueError: \n
^\\\\circ\n ^\nParseSyntaxException: Expected {accent | symbol | function | operatorname | group | frac | dfrac | binom | genfrac | overset | underset | sqrt | overline | text | boldsymbol | substack}, found '\\'  (at char 1), (line:1, col:2)\n"]
```

**Comment by g7gpr** [comment]
I suspect #378 will fix this, if so I'll close

**Comment by g7gpr** [comment]
Resolved.
