### ISSUE TITLE
New distortion type crashes CAMS-compatible cameras

### ISSUE THREAD

**Issue by tammojan** [CroatianMeteorNetwork/RMS#76]
Since the CAL-format doesn't (yet?) understand the new radial distortion types, there is a crash in RMS:
```
2021/05/21 02:43:57-INFO-Reprocess-line:320 - Flat saved to: /home/pi/RMS_data/CapturedFiles/NL000E_20210520_202414_904810/flat.bmp
2021/05/21 02:43:57-INFO-Reprocess-line:401 - Generating a CAMS FTPdetectinfo file...
Traceback (most recent call last):
  File "RMS/StartCapture.py", line 947, in <module>
    upload_manager=upload_manager, detect_end=cml_args.detectend, resume_capture=cml_args.resume)
  File "RMS/StartCapture.py", line 448, in runCapture
    detection_results=detection_results, nodetect=nodetect)
  File "/home/pi/vRMS/lib/python3.7/site-packages/RMS-0.1-py3.7-linux-armv7l.egg/RMS/Reprocess.py", line 404, in processNight
    cal_file_name = writeCAL(night_data_dir, config, platepar)
  File "/home/pi/vRMS/lib/python3.7/site-packages/RMS-0.1-py3.7-linux-armv7l.egg/RMS/Formats/CAL.py", line 58, in writeCAL
    platepar.y_poly_fwd[11], platepar.y_poly_fwd[10] = platepar.y_poly_fwd[10], platepar.y_poly_fwd[11]
IndexError: index 10 is out of bounds for axis 0 with size 7
```
This also aborts any uploads.

**Comment by dvida** [comment]
fixed
