### ISSUE TITLE
Problem using SkyFit2

### ISSUE THREAD

**Issue by AstroBath** [CroatianMeteorNetwork/RMS#98]
Built RMS on Windows and then Ubuntu to instructions to run SkyFit2 using `python -m Utils.SkyFit2 C:\Users\sholbeche\Downloads\20210807_UK0038\UK0038_20210807_202419_529241 --config .`

Both instances run but fits images are not shown in SkyFit2 but histogram shows light detected. Using `python -m RMS.Astrometry.SkyFit C:\Users\sholbeche\Downloads\20210807_UK0038\UK0038_20210807_202419_529241 --config .`
images are shown ok

The error in SkyFit2 on each screen refresh is:
```
Traceback (most recent call last):
  File "C:\Users\sholbeche\Anaconda3\envs\rms\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 834, in paint
    self.render()
  File "C:\Users\sholbeche\Workspace\Meteors\RMS\RMS\Routines\CustomPyqtgraphClasses.py", line 644, in render
    efflut = pg.fn.rescaleData(ind, scale=255./levdiff,
AttributeError: module 'pyqtgraph' has no attribute 'fn'
```

**Comment by dvida** [comment]
Is this under Windows or Ubuntu? The Ubuntu instructions differ a bit, they are here: https://docs.google.com/document/d/19ImeNqBTD1ml2iisp5y7CjDrRV33wBeF9rtx3mIVjh4/edit#heading=h.hlb99n4cn698
